/** Local copies of landing page assets */
export const landingAssets = {
  heroDashboard: "/landing/hero-dashboard.png",
  heroDashboardV2: "/landing/hero-dashboard-v2.png",
  heroDashboardFigma: "/landing/hero-dashboard-figma.png",
  askAstrydPrompt: "/landing/ask-astryd-prompt.png",
  featureAskAstryd: "/landing/feature-ask-astryd.png",
  featureCrm: "/landing/feature-crm.png",
  featureFinance: "/landing/feature-finance.png",
  featureInventory: "/landing/feature-inventory.png",
  financeDashboard: "/landing/finance-dashboard.png",
  touchpointHero: "/landing/touchpoint-hero.png",
  hardware1: "/landing/hardware-1.png",
  hardware2: "/landing/hardware-2.png",
  hardware3: "/landing/hardware-3.png",
  hardware4: "/landing/hardware-4.png",
  paymentsDashboard: "/landing/payments-dashboard.png",
  payrollTeam: "/landing/payroll-team.png",
  crmPayment: "/landing/crm-payment.png",
  crmPhone: "/landing/crm-phone.png",
  crmStreet: "/landing/crm-street.png",
  verticalRestaurants: "/landing/vertical-restaurants.png",
  verticalRetail: "/landing/vertical-retail.png",
  verticalBeauty: "/landing/vertical-beauty.png",
  verticalFitness: "/landing/vertical-fitness.png",
  chatTailLeft: "/landing/chat-tail-left.png",
  chatTailRight: "/landing/chat-tail-right.png",
  features: {
    pos: "/landing/features/pos-dashboard-figma.png",
    menus: "/landing/features/menus-storefront-figma.png",
    inventory: "/landing/features/inventory-management-figma.png",
    tables: "/landing/features/tables-bookings-figma.png",
    memberships: "/landing/features/memberships-figma.png",
    payroll: "/landing/features/time-payroll-figma.png",
    accountsPayable: "/landing/features/accounts-payable-figma.png",
    invoicing: "/landing/features/invoicing-receivables-figma.png",
    crm: "/landing/features/crm-engagement-figma.png",
  },
  industry: {
    restaurants: "/landing/industry/restaurants-figma.png",
    fitness: "/landing/industry/fitness-figma.png",
    retail: "/landing/industry/retail-figma.png",
    salon: "/landing/industry/salon-figma.png",
    personalCare: "/landing/industry/personal-care-figma.png",
    business: "/landing/industry/business-figma.png",
  },
  integrations: [
    "/landing/integrations/delivery.jpg",
    "/landing/integrations/pos.jpg",
    "/landing/integrations/payments.jpg",
    "/landing/integrations/social.jpg",
    "/landing/integrations/inventory.jpg",
    "/landing/integrations/booking.jpg",
    "/landing/integrations/analytics.jpg",
    "/landing/integrations/team.jpg",
    "/landing/integrations/retail.jpg",
    "/landing/integrations/fitness.jpg",
    "/landing/integrations/coffee.jpg",
    "/landing/integrations/salon.jpg",
    "/landing/integrations/kitchen.jpg",
    "/landing/integrations/invoice.jpg",
    "/landing/integrations/scheduling.jpg",
  ],
} as const;
